Repository Hoto-Mocha/ARranged-Pixel-Dungeon, pull requests merged in 2021-09, with the labels that each got.

#17 문서 수정
  mod-docs/3번째 보조 직업.md
  mod-docs/talent_icons.png
  mod-docs/거너.md
  mod-docs/녹픽던 모딩 기획서.md
  mod-docs/메시지 텍스트.properties
  mod-docs/새로운 아이템.md
  mod-docs/총기 메커니즘.md
Labels: 문서

#19 각종 수정
  mod-docs/3번째 보조 직업.md
  mod-docs/items.png
  mod-docs/녹픽던 모딩 기획서.md
  mod-docs/새로운 아이템.md
  mod-docs/총기 메커니즘.md
Labels: 문서

#22 총기 추가
  core/src/main/assets/messages/items/items_ko.properties
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/Char.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/buffs/Preparation.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/hero/Hero.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/scrolls/exotic/ScrollOfEnchantment.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/ammunition/ArmorPiercing.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/ammunition/HollowPoint.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/ammunition/Incendiary.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/CrudePistol.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/Gun.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/Handgun.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/HuntingRifle.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/ShotGun.java
Labels: 기능 추가

#28 [Fix] 재장전 및 텍스트 관련 오류 수정
  core/src/main/assets/messages/items/items_ko.properties
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/hero/HeroClass.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/AssultRifle.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/CrudePistol.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/DualPistol.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/Gun.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/Handgun.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/HuntingRifle.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/MachineGun.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/MagnumPistol.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/RocketLauncher.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/ShotGun.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/SniperRifle.java
  core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/WornShortsword.java
Labels: 버그
